
name: Deploy Hexo

on:
  push:
    branches:
      - main 

# 给予该脚本发布 Pages 的最高权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g hexo-cli

    - name: Build Static Files
      run: |
        hexo clean
        hexo generate
        # 在编译出的网页目录里放入阻断 Jekyll 的控制文件
        touch public/.nojekyll

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public' 

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 
